runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "1.6.1"

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /img
  static_dir: img
- url: /.*
  script: main.app
# [END handlers]
